# Generated by Django 6.0.4 on 2026-04-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_news_options_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='custom_design',
            field=models.JSONField(blank=True, null=True, verbose_name='Кастомний дизайн'),
        ),
    ]
