# Generated by Django 6.0.4 on 2026-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_club_custom_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='core.book', verbose_name='Книги клубу'),
        ),
    ]
