# Generated by Django 6.0.4 on 2026-05-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='core.genre'),
        ),
    ]
