# Generated by Django 6.0.4 on 2026-05-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='currently_reading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поточна книга'),
        ),
    ]
